;;; highlight-global-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from highlight-global.el

(register-definition-prefixes "highlight-global" '("buffer-highlight-list" "check-whether-highlighted" "clear-" "find-and-use-face" "force-highlight-frame" "get-thing-to-highlight" "global-highlight-list" "highlight-" "new-" "release-face" "unhighlight-window" "update-highlight-fixup"))

;;; End of scraped data

(provide 'highlight-global-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; highlight-global-autoloads.el ends here
